### ISSUE TITLE
Can't load df dcnn file pachi_19x19.exe crash

### ISSUE THREAD

**Issue by jun63cn** [pasky/pachi#114]
win7x64  pachi -t =5000:15000 --dcnn=df
Pachi 12.40 (Jowa)
git a372ddf5 (master)
x86-64 dcnn build, Mar 31 2019

Random seed: 1554190993
F0402 20:00:33.743199 24000 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Reshape (known types: Convolution, Flatten, Input, ReLU, Softmax)
*** Check failure stack trace: ***
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000
    @   0000000000000000

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

D:\Downloads\Pachi>

**Comment by lemonsqueeze** [comment]
Ha, yes. Forgot to update static builds for darkforest dcnn.
Should be fixed soon...

**Comment by lemonsqueeze** [comment]
Updated [release](https://github.com/pasky/pachi/releases/tag/pachi-12.40), should work now.

**Comment by jun63cn** [comment]
It's works.    Thank you very much!
