### ISSUE TITLE
Compiled from source with DCNN support Pachi 12.40 uses only 1 CPU core

### ISSUE THREAD

**Issue by GD-fix** [pasky/pachi#121]
OS:
OpenSUSE Tumbleweed

Non-default compile parameters:
Makefile -
DOUBLE_FLOATING=1
PREFIX  ?= /usr
build.h:  Makefile
patternsp.h -
#define spatial_hash_bits 30

The engine used only 1 core during thinking (with --nodcnn too and on pondering too) regardless of given (and rightly repeated on engine loading output) threads parameter value, while binary version (pachi-12.40-amd64) used given number of cores.
But in sparring with itself compiled engine (only on white side) used given number (2) of cores (but used half the amount of memory: 4 GiB instead of 8 GiB after loading before game starting, while version compiled without using DCNN on OpenSUSE 12.3 always used given number of cores and 8 GiB of memory on start up)...

Is it possible to compile Pachi with DCNN from source so that this engine will use cores, how it uses pachi-12.40-amd64?
Thanks in advance.

P.S. All compiled versions (on all systems) launched without "make install".

**Comment by GD-fix** [comment]
The PachiDCNN 12.50 version keeps the bug. Moreover, the Pachi 12.50 version became weaker (http://rugo.ru/read.php?2,68490,8034224,page=21#msg-8034224)...

**Comment by lemonsqueeze** [comment]
Hi,
Sorry i don't have time to investigate this at the moment, but looks like there is something wrong with your build. It's also possible something strange is happening when building on OpenSuse, which i haven't tried. If you want this fixed try troubleshooting the problem yourself :
- do the same build on another system to find if it's a Suse-related issue (for example ubuntu)
- bring it up in the debugger and find what's going on with core logic

**Comment by GD-fix** [comment]
The pachi-12.50-amd64 --dcnn=darkforest cann't beat the simple (without any NN) Ray (http://rugo.ru/read.php?2,68490,8034225,page=21#msg-8034225)...

**Comment by GD-fix** [comment]
Hi!

"...bring it up in the debugger and find what's going on with core logic..."
On console (on engine loading output) threads parameter value is true. How I must bring it up in the debugger (step by step)?

Thanks in advance.

**Comment by GD-fix** [comment]
v. 12.60: -all the same...

**Comment by GD-fix** [comment]
v. 12.70: - doesn't compile at all.
Issue is closed due to the lack of any meaning...
