### ISSUE TITLE
gmake[1]: *** No rule to make target '.git/HEAD', needed by 'build.h'.  Stop.

### ISSUE THREAD

**Issue by yurivict** [pasky/pachi#122]
Tarballs downloaded from github don't have the ```.git``` directory.
This lookup should be made optional.

**Comment by lemonsqueeze** [comment]
See issue #78.

**Comment by yurivict** [comment]
Tarball doesn't have ```.git```, so it doesn't work with tarballs.
The package builder has to use tarballs, it never checks anything out from git.
