### ISSUE TITLE
Pachi can not be set as Analyser in Sabaki,or it would display bad argument.

### ISSUE THREAD

**Issue by Saturday-morning** [pasky/pachi#134]
```
pachi> name 
= Pachi
pachi> version 
= 12.45
pachi> protocol_version 
= 2
pachi> list_commands 
= protocol_version
name
echo
version
（and a lot of commands）
Pachi 12.45 (Jowa)
git 74f57b47 (master)
i686 dcnn build, Apr  8 2020  
Random seed: 1588185465
Scoring: using mcts (possibly inaccurate)
Loaded Darkforest dcnn for 19x19
Loaded spatial dictionary of 18016 patterns.
Loaded 18101 gammas.
Checking gammas ... OK
Threads: 2


#when I chick analyze, or push F4:
IN: name
IN: version
IN: protocol_version
IN: list_commands
pachi> komi 7.5
= IN: komi 7.5
pachi> boardsize 19
= IN: boardsize 19
pachi> clear_board 
= IN: clear_board
○ pachi> lz-analyze B 50
? bad argument
IN: lz-analyze B 50
```

(Windows10,sabaki ia32 portable and pachi)
When I set Pachi as an analyzer, Sabaki puts" the bad arguement",except this is nothing.
However, when I set Pachi as the analyzer and the white go player at the same time, the heat map and the win rate curve can be successfully displayed, but when the Pachi calculation is completed, the heat map will disappear and "the bad arguement" is displayed.
Is this is a problem,or normal？The issue is belong to Pachi or Sabaki?
……
（My English is not well,so this is form google translate,and I edit it.）
![图片](https://user-images.githubusercontent.com/53111574/80636389-f561b880-8a8f-11ea-824e-23f9acdcb63e.png)
Looking for help…
Thanks.

**Comment by lemonsqueeze** [comment]
Hi,
Looks like Sabaki is getting confused because it's getting both Pachi output and debug messages mixed up. Pachi answers gtp commands on standard output and uses standard error for logging by default. Normally Sabaki should ignore standard error. Depending on how you run Pachi, i guess it's also possible something in between is causing both channels to merge which would confuse Sabaki just the same.

As a workaround you can pass `-o pachi.log` option to Pachi to log to a file instead, or `-d 0` to suppress logging altogether.

**Comment by Saturday-morning** [comment]
![图片](https://user-images.githubusercontent.com/53111574/80736724-1801d900-8b45-11ea-973c-a5318679fdae.png)
![图片](https://user-images.githubusercontent.com/53111574/80736765-25b75e80-8b45-11ea-8ff6-5bc1069690e9.png)
![图片](https://user-images.githubusercontent.com/53111574/80736850-4a133b00-8b45-11ea-90b1-d43a23300ab8.png)

- thanks for reply. However,the option `-d 0` may be not working.

- P1:I set  `-d 0` to 'test'

- P2:I have run 'test'

- P3:After setting it as analyser.

------------------------------------------------------------------------------------------------------------

- I also use the batch file keep option: `pachi.exe -d 0`.I double-chick it and there was only an empty cmd window ... I think those logging had disappeared, but when I ran it with Sabaki and set it as the analyzer, the "bad arguement" appeared again.However,I have an another try.The test.bat    :

![图片](https://user-images.githubusercontent.com/53111574/80740788-32d74c00-8b4b-11ea-8efb-96ebeef124e4.png)
I ran those GTP commands copied form Sabaki:
![图片](https://user-images.githubusercontent.com/53111574/80741001-834ea980-8b4b-11ea-89a0-2130ac13cbf3.png)

- We can see the  "bad arguement" is an output of Pachi.

-----------------------------------------------------------------------------------------------------------
but I watch it:
```
● pachi> lz-genmove_analyze W 50
= info move (…)
play Q16
IN: lz-genmove_analyze W 50
Move:   1  Komi: 7.5  Handicap: 0  Captures B: 0 W: 0  
      A B C D E F G H J K L M N O P Q R S T        A B C D E F G H J K L M N O P Q R S T  
    +---------------------------------------+    +---------------------------------------+
 19 | . . . . . . . . . . . . . . . . . . . | 19 | : : : : : : : : : : : : : : : : : : : |
 18 | . . . . . . . . . . . . . . . . . . . | 18 | : : : : : : : : : : : : : : : : : : : |
 17 | . . . . . . . . . . . . . . . . . . . | 17 | : : : : : : : : : : : : : : : : : : : |
 16 | . . . . . . . . . . . . . . . . . . . | 16 | : : : : : : : : : : : : : : : : : : : |
 15 | . . . . . . . . . . . . . . . . . . . | 15 | : : : : : : : : : : : : : : : : : : : |
 14 | . . . . . . . . . . . . . . . . . . . | 14 | : : : : : : : : : : : : : : : : : : : |
 13 | . . . . . . . . . . . . . . . . . . . | 13 | : : : : : : : : : : : : : : : : : : : |
 12 | . . . . . . . . . . . . . . . . . . . | 12 | : : : : : : : : : : : : : : : : : : : |
 11 | . . . . . . . . . . . . . . . . . . . | 11 | : : : : : : : : : : : : : : : : : : : |
 10 | . . . . . . . . . . . . . . . . . . . | 10 | : : : : : : : : : : : : : : : : : : : |
  9 | . . . . . . . . . . . . . . . . . . . |  9 | : : : : : : : : : : : : : : : : : : : |
  8 | . . . . . . . . . . . . . . . . . . . |  8 | : : : : : : : : : : : : : : : : : : : |
  7 | . . . . . . . . . . . . . . . . . . . |  7 | : : : : : : : : : : : : : : : : : : : |
  6 | . . . . . . . . . . . . . . . . . . . |  6 | : : : : : : : : : : : : : : : : : : : |
  5 | . . . . . . . . . . . . . . . . . . . |  5 | : : : : : : : : : : : : : : : : : : : |
  4 | . . . X). . . . . . . . . . . . . . . |  4 | : : : : : : : : : : : : : : : : : : : |
  3 | . . . . . . . . . . . . . . . . . . . |  3 | : : : : : : : : : : : : : : : : : : : |
  2 | . . . . . . . . . . . . . . . . . . . |  2 | : : : : : : : : : : : : : : : : : : : |
  1 | . . . . . . . . . . . . . . . . . . . |  1 | : : : : : : : : : : : : : : : : : : : |
    +---------------------------------------+    +---------------------------------------+
pachi> protocol_version 
= 2
mcowner 0.28s
dcnn in 0.71s
dcnn = [ Q16 D16 Q4  Q3  C16 R17 R16 Q17 C17 R3  C15 R4  D17 P17 R15 P3  Q5  E16 D15 P16 ]
       [ 28  22  22  9   8   2   1   1   0   0   0   0   0   0   0   0   0   0   0   0   ]
(avg score -4.133232/8237; dynkomi's -4.133232/8237 value 0.484764/8237)
*** WINNER is Q16 with score 0.5143 (3844/8237:8237/8237 games), extra komi 0.000000
genmove in 5.95s, mcts 4.96s (1660 games/s, 830 games/s/thread)
Move:   2  Komi: 7.5  Handicap: 0  Captures B: 0 W: 0  Score Est: W+3.5
      A B C D E F G H J K L M N O P Q R S T        A B C D E F G H J K L M N O P Q R S T  
    +---------------------------------------+    +---------------------------------------+
 19 | . . . . . . . . . . . . . . . . . . . | 19 | , , , , , , , , , , , , , , , , , , , |
 18 | . . . . . . . . . . . . . . . . . . . | 18 | , , , , , , , , , , , , , , , , , , , |
 17 | . . . . . . . . . . . . . . . . . . . | 17 | , , , , , , , , , , , , , , , , , , , |
 16 | . . . . . . . . . . . . . . . O). . . | 16 | , , , , , , , , , , , , , , , , , , , |
 15 | . . . . . . . . . . . . . . . . . . . | 15 | , , , , , , , , , , , , , , , , , , , |
 14 | . . . . . . . . . . . . . . . . . . . | 14 | , , , , , , , , , , , , , , , , , , , |
 13 | . . . . . . . . . . . . . . . . . . . | 13 | , , , , , , , , , , , , , , , , , , , |
 12 | . . . . . . . . . . . . . . . . . . . | 12 | , , , , , , , , , , , , , , , , , , , |
 11 | . . . . . . . . . . . . . . . . . . . | 11 | , , , , , , , , , , , , , , , , , , , |
 10 | . . . . . . . . . . . . . . . . . . . | 10 | , , , , , , , , , , , , , , , , , , , |
  9 | . . . . . . . . . . . . . . . . . . . |  9 | , , , , , , , , , , , , , , , , , , , |
  8 | . . . . . . . . . . . . . . . . . . . |  8 | , , , , , , , , , , , , , , , , , , , |
  7 | . . . . . . . . . . . . . . . . . . . |  7 | , , , , , , , , , , , , , , , , , , , |
  6 | . . . . . . . . . . . . . . . . . . . |  6 | , , , , , , , , , , , , , , , , , , , |
  5 | . . . . . . . . . . . . . . . . . . . |  5 | , , , x , , , , , , , , , , , , , , , |
  4 | . . . X . . . . . . . . . . . . . . . |  4 | , , x X x , , , , , , , , , , , , , , |
  3 | . . . . . . . . . . . . . . . . . . . |  3 | , , , x , , , , , , , , , , , , , , , |
  2 | . . . . . . . . . . . . . . . . . . . |  2 | , , , , , , , , , , , , , , , , , , , |
  1 | . . . . . . . . . . . . . . . . . . . |  1 | , , , , , , , , , , , , , , , , , , , |
    +---------------------------------------+    +---------------------------------------+

IN: protocol_version
pachi> clear_board 
= 
○ pachi> play B D4
= 
IN: clear_board
IN: play B D4
● pachi> lz-analyze W 50
? bad argument
IN: lz-analyze W 50
```

So,I think:

> When I set Pachi as an analyzer, Sabaki puts" the bad arguement",except this is nothing.
However, when I set Pachi as the analyzer and the white go player at the same time, the heat map and the win rate curve can be successfully displayed, but when the Pachi calculation is completed, the heat map will disappear and "the bad arguement" is displayed.

I think it is because the difference between `lz-genmove_analyze W 50` and `lz-analyze W 50`.
Pachi supports `lz-genmove_analyze W 50` perfectly,but the sopport (or compatibility?) to `lz-analyze W 50` may be need some fix.(And I loading leelazero on Sabaki,after setting analyser,it will show  the heat map and the win rate curve,and typing:info move (…)     )

But I don't know the problem is just on my computer…I will try more later[windows/linux
(about 11 days later),sabaki portable/install(maybe tomorrow)].
Thanks.

**Comment by lemonsqueeze** [comment]
You're right, the problem is Pachi doesn't know `lz-analyze W 50` syntax,
only `lz-analyze 50` syntax is supported right now.
Fortunately this is easy to fix. Could you try this [pachi.exe](https://github.com/pasky/pachi/files/4564150/pachi.zip), see if it works for you ?

**Comment by Saturday-morning** [comment]
Sure,and the `bad arguement` has disappeared.
![图片](https://user-images.githubusercontent.com/53111574/80813613-e9dfd000-8bfc-11ea-86a7-1a7de5242d4b.png)

Although now it has not the the heat map and the win rate curve,next picture shows that Pachi keeps running.(but memory will be the next problem,because Pachi keeps running,running and runnin,until it popup try to increase max_tree_side or go to next step)

![图片](https://user-images.githubusercontent.com/53111574/80813776-3fb47800-8bfd-11ea-81f5-1f000730d6f9.png)

![图片](https://user-images.githubusercontent.com/53111574/80814842-31675b80-8bff-11ea-9141-f24b84d7514d.png)

**Comment by lemonsqueeze** [comment]
Ok, i see it too.
There was a newline issue which was confusing Sabaki.

If you try this [pachi.exe](https://github.com/pasky/pachi/files/4565955/pachi.zip) heat map should work now when you toggle analysis. You can toggle analysis on and off, as long as tree memory limit is not reached it should be ok.

There is still the issue that if tree memory limit is reached Pachi stops but Sabaki keeps waiting forever and you have to detach and reattach the engine. Not sure why this is happening, i'd suggest using a big enough max_tree_size so that it doesn't happen for now =)

I haven't found a way to get heat map output during genmove with either Leela-Zero or Pachi.
Have you ?

**Comment by lemonsqueeze** [comment]
By the way looks like there is a typo in your command line:
```
-t =10000:35000 --fuseki-time =8000 resign_threshold=0.20 threads=2,max_tree_size=320,pondering
```
should be:
```
-t =10000:35000 --fuseki-time =8000 resign_threshold=0.20,threads=2,max_tree_size=320,pondering
```

It should give an error really, because of space only `resign_threshold=0.20` part is used !

**Comment by Saturday-morning** [comment]
![图片](https://user-images.githubusercontent.com/53111574/80865537-b82e3e00-8cbc-11ea-8588-f0b96705afff.png)
![图片](https://user-images.githubusercontent.com/53111574/80865573-f6c3f880-8cbc-11ea-8bab-f6e3fede24e9.png)
Success.

----------------------------------------------------------------------------
Is the following heat map output?
```
desired 9.00, worst 10.00, clock [1] 0.00 + 10.00/1*1, lag 2.00

mcowner 0.13s

dcnn in 0.22s

dcnn = [ Q16 C16 D16 Q17 D17 R16 Q14 K10 C15 P17 R17 Q4  E17 C17 Q3  R15 P15 P16 Q15 D15 ]

       [ 30  23  19  11  3   2   1   1   0   0   0   0   0   0   0   0   0   0   0   0   ]

info move Q16 visits 978 winrate 4959 prior 10000 order 0 pv Q16 O17 R14 info move D16 visits 873 winrate 5120 prior 8438 order 1 pv D16 Q16 Q4 O3 info move C16 visits 837 winrate 5161 prior 8415 order 2 pv C16 Q3 Q5 

info move Q16 visits 1653 winrate 5021 prior 10000 order 0 pv Q16 D17 D15 C15 C14 C16 info move D16 visits 1382 winrate 5057 prior 8438 order 1 pv D16 Q16 Q4 O3 info move C16 visits 1366 winrate 5109 prior 8415 order 2 pv C16 Q3 Q5 

info move Q16 visits 1943 winrate 4981 prior 10000 order 0 pv Q16 D16 F17 C14 Q4 info move D16 visits 1901 winrate 5092 prior 8438 order 1 pv D16 Q16 Q4 R6 info move C16 visits 1667 winrate 5122 prior 8415 order 2 pv C16 E16 E17 F17 D17 G16 info move Q17 visits 644 winrate 5201 prior 6258 order 3 pv Q17 D16 C14 F17 

info move D16 visits 3433 winrate 5083 prior 8438 order 0 pv D16 Q16 Q4 R6 O3 info move Q16 visits 3394 winrate 5008 prior 10000 order 1 pv Q16 D16 F17 C14 Q4 info move C16 visits 3165 winrate 5134 prior 8415 order 2 pv C16 Q17 Q3 Q5 R5 R6 info move Q17 visits 1149 winrate 5178 prior 6258 order 3 pv Q17 D16 C14 F17 

info move Q16 visits 5356 winrate 5067 prior 10000 order 0 pv Q16 D16 Q3 Q5 R7 R3 R2 R4 N3 info move C16 visits 4536 winrate 5110 prior 8415 order 1 pv C16 Q17 Q3 Q5 R5 R6 R4 info move D16 visits 4503 winrate 5058 prior 8438 order 2 pv D16 Q3 Q16 O17 R14 info move Q17 visits 1563 winrate 5060 prior 6258 order 3 pv Q17 D16 C14 F17 B16 C17 

(avg score -1.569023/19833; dynkomi's -1.569023/19833 value 0.490445/19833)

*** WINNER is Q16 with score 0.5052 (5697/19831:19831/19833 games), extra komi 0.000000

genmove in 8.77s, mcts 8.42s (2354 games/s, 1177 games/s/thread)

info move Q16 visits 5697 winrate 5051 prior 10000 order 0 pv Q16 D16 Q3 Q5 R7 R3 R2 R4 N3 info move D16 visits 5623 winrate 5093 prior 8438 order 1 pv D16 Q3 Q17 R15 info move C16 visits 5124 winrate 5117 prior 8415 order 2 pv C16 Q17 Q3 Q5 R5 R6 R4 info move Q17 visits 3309 winrate 5161 prior 6258 order 3 pv Q17 D16 C14 F17 B16 C17 

tree pruned in 0.016s, prev 0.0s ago, dest depth 13 wanted 3, size 34294800->9766240/62914560, playouts 5697
```

**Comment by lemonsqueeze** [comment]
Yes, `info move ...` lines are the heat map output.
Sabaki hides them but you see them if you run Pachi directly.
I fixed a few other issues, I'll make a new release soon.
Thanks for helping with this

**Comment by Saturday-morning** [comment]
You are welcome.


I have a typo again…  
It‘s not FoxFTP,is FoxGTP,whose funtion is like the KGS connector…
https://www.foxwq.com/soft/aiprogramandmanual.html

**Comment by lemonsqueeze** [comment]
Pachi 12.50 is [released](https://github.com/pasky/pachi/releases/tag/pachi-12.50).
Please let me know if you see issues with it.

**Comment by Saturday-morning** [comment]
- I have  seen it. (sorry,I have being gone to school.So I only have time on Saturday afternoon.And I use an another computer,which runs Ubuntu 20.04LTS)

--------------------------------------
![5 24](https://user-images.githubusercontent.com/53111574/82735262-e8647c00-9d52-11ea-8b60-427b2f5ccdf8.png)

- It's working on Ubuntu.(ppa looks like not supporting 20.04.So I try building myself)

----------------------------------------
And I found a new way to find out the heat map output.Using Go Review Partner 0.15
![5 24-2](https://user-images.githubusercontent.com/53111574/82735747-8b6ac500-9d56-11ea-98d7-4ec831117d22.png)
Put the test icon.There will be a window where can input gtp command,so just input lz-analyze W 50 in it.(This way does not depends on windows.)

**Comment by Saturday-morning** [comment]
Since 12.50 released,the problem(s?) has solved,and new     Characteristic has emerged.（the phrase is translated）It's beneficial to close this issue.Thanks for developers!
-------------------------------------------------------------------------------
帕奇12.50已经发布，问题应该已经被解决了，新的特性已经出现。此时最好的做法还是关闭这个issue。另外当然得说一句，感谢开发者，感谢大家。
