### ISSUE TITLE
About not being able to run in sabaki

### ISSUE THREAD

**Issue by hope366** [pasky/pachi#139]
Hello.
I tried to run the latest pachi-12.50 with sabaki, but I got a message that pachi.exe is dangerous by the anti-virus software.
I selected "Ignore and run" and it worked, but is there any problem with pachi.exe?

https://github.com/wonsiks/BadukMegapack
Baduk Megapack", which can be downloaded from here, has a file pachi_19x19.exe in addition to pachi.exe, and no error message was shown when using this file.

Translated with www.DeepL.com/Translator (free version)

**Comment by lemonsqueeze** [comment]
Hi,
It's most likely ok, the windows Pachi binaries distributed here are compressed with [upx](https://upx.github.io/) executable packer to reduce file size, the anti-virus probably thinks it's suspicious activity when it sees a program uncompress itself.

pachi_19x19.exe is 19x19-only version of Pachi. I didn't include it in this release but from your report it looks like wonsiks built his own. Probably he didn't pack it with upx and so no warnings. If you look at pachi_19x19.exe file size that should tell us if this is the case.

**Comment by hope366** [comment]
Thank you for your quick response.
This is the first time I've heard of UPX. Thank you for sharing this with us.
The pachi.exe included in the megapack is 6,479KB, which is exactly the same size as the Pachi-12.50's pachi.exe.
Also, the pachi_19x19.exe included in the megapack is 6,469KB.

**Comment by lemonsqueeze** [comment]
Looks like this is pachi_19x19.exe from Pachi 12.45.
wonsiks may have forgotten to remove it when he packaged Pachi 12.50.

**Comment by hope366** [comment]
I think wonsiks either forgot to delete pachi 12.45's pachi_19x19.exe or intentionally left it behind (not feeling the need to create pachi 12.50's pachi_19x19.exe).

Thank you very much for sharing this interesting information with us.

**Comment by hope366** [comment]
I'd like to close it as it seems to have solved the problem for the time being.
