### ISSUE TITLE
play B B19,lz-genmove_analyze w 50,pachi crash

### ISSUE THREAD

**Issue by Saturday-morning** [pasky/pachi#142]
double chick to open pachi.
In Cmd(on Windows 10 32bit)

input：
komi 7.5
boardsize 19
clear_board
play B B19
lz-genmove_analyze w 50

```
Pachi 12.50 (Jowa)
git fddc8583 (master)
i686 dcnn build, May 20 2020
Random seed: 1596284477
Scoring: using mcts (possibly inaccurate)
Loaded Detlef's 54% dcnn for 19x19
Loaded spatial dictionary of 18016 patterns.
Loaded 18101 gammas.
Checking gammas ... OK
Threads: 2
komi 7.5
IN: komi 7.5
=
boardsize 19
IN: boardsize 19
clear_board
IN: clear_board
=
play B B19
IN: play B B19
=
lz-genmove_analyze w 50
IN: lz-genmove_analyze w 50
Move:   1  Komi: 7.5  Handicap: 0  Captures B: 0 W: 0
………………………(the go board)
 desired 9.00, worst 10.00, clock [1] 0.00 + 10.00/1*1, lag 2.00
mcowner 0.13s
dcnn in 0.19s 
dcnn = [ Q16 Q17 D16 Q14 R16 D17 D4  P17 K10 Q4  R17 R15 P15 P16 Q15 C17 C16 K11 O16 R4  ]
[ 58  21  4   2   2   2   1   1   1   0   0   0   0   0   0   0   0   0   0   0   ]                                                                                   
```

**Then，Pachi will close.**

When I set pachi as white player,and play B19,Pachi will close.
But I do the same thing in GoGUI,Pachi run successfully.
After checking the GTP shell,I think the problem is about` lz-genmove_analyze w 50`
because Sabaki will use this （even not in analyse mode）

Actually,the black points have the same problem.
By the way,the photo is not accurate completely ,because the wrong and normal points are changing.(The picture just the one practice.)
Such as J18,I try 3 times,two are success,one is fail.
Such as Q3,five are fail and one is success.

But B19 always fails.

![图片](https://user-images.githubusercontent.com/53111574/89101312-6028e400-d431-11ea-8884-cb3ba79d5cb1.png)

（
To safe time to produce the picture,I:
`pachi.exe -t =1000`
）

Thanks.

**Comment by lemonsqueeze** [comment]
I see the crash too, thanks for spotting this.
