### ISSUE TITLE
What only 1 issue?

### ISSUE THREAD

**Issue by peepo** [pasky/pachi#2]
hey welcome to github,
how painful was that?

could not find link to email forum here, homepage, other repository, google etc,
am on strange box ~5.29Gb download, so excuse me.

did you try
sudo apt-get install pachi
it would be nice to have a debian maintainer.

am planning to set pachi up on 8 core dedicated box,
big.little architecture so don't get too excited...

be in touch

~:"

**Comment by pasky** [comment]
It would be totally nice to have Pachi in debian! But I'm not sure if a github issue will help with that, maybe rather file RFP or ITP in Debian's BTS.
