### ISSUE TITLE
time settings documentation

### ISSUE THREAD

**Issue by nsajko** [pasky/pachi#20]
It would be nice if you gave a few examples of time setup command line usage.

**Comment by pasky** [comment]
Pachi can smartly deal with a variety of time settings (personally, I'd recommend canadian byoyomi to maximize efficient time allocation). However, most of these are accessible only via GTP, that is by the frontend keeping track of time - e.g. KGS or gogui (if it can do that).

But via the command line, only a few modes are available:

  * **-t =5000** will not fix the time per se, but number of Monte Carlo playouts per move; that is, Pachi will play fast on a fast computer, slow on a slow computer, but it should have fixed strength

  * **-t 20** will fix the number of seconds spent per move.  Pachi will spend a little less to allow for network latency and other unexpected slowdowns. This is the same as one-period Japanese byoyomi.

  * **-t _600** will fix the number of seconds spent per the whole game. Pachi will allocate time to fit the whole game in the "sudden death" regime.

**Comment by nsajko** [comment]
Awesome :)

**Comment by roy7** [comment]
Does pachi recognize commands like time_setting and time_left when they arrive from the server when playing via gtp?

**Comment by lemonsqueeze** [comment]
README and `pachi -h` should be more helpful now.
