### ISSUE TITLE
pachi: search.c:417: uct_search_check_stop: Assertion `!(ti->dim == TD_GAMES && ti->len.games < 500)' failed.

### ISSUE THREAD

**Issue by nsajko** [pasky/pachi#21]
[pachi_gtp.txt](https://github.com/pasky/pachi/files/141057/pachi_gtp.txt)

I ran it with:
`pachi -t =120 threads=6,max_tree_size=5000`

same thing with:
`pachi -t =30 threads=8,max_tree_size=3072`
!!!

**Comment by pasky** [comment]
Hi, 120 playouts per move is way too low; various heuristics are too
unstable, which is why this is prevented.  Typical speed of Pachi is
1000 playouts per second or more on 19x19.

**Comment by nsajko** [comment]
I had confused the seconds per move with playouts per move options :)
