### ISSUE TITLE
strange(?) behavior

### ISSUE THREAD

**Issue by nsajko** [pasky/pachi#22]
I start a gogui game of pachi vs pachi with:
`pachi -t 60 threads=6,max_tree_size=6000`
, the first surprise is that it plays rubbish moves, eg. first move is K17.

The second surprise is that it first "thinks" for 50 seconds on the first move and then instead of doing that for all other moves makes all of them at once!

**Comment by pasky** [comment]
Could it be related to some parameters you have set up in gogui?  How
exactly did you pair the pachis?

**Comment by nsajko** [comment]
I set "Computer Color" to "Both".

**Comment by pasky** [comment]
Did you set any time limits inside gogui?  When you play pachi yourself,
does it behave ok?

**Comment by nsajko** [comment]
I didn't set a time limit.

I am playing black against `pachi -t 60 threads=7,max_tree_size=6000`, and it again played its first move on the side instead of in the corner (I'm pretty sure that's a bad move);
but it didn't play other moves instantaneously.
I'm going to try playing white now.

**Comment by pasky** [comment]
The opening can be a bit wacky, especially if you haven't downloaded
the large patterns and aren't using an opening book.  But Pachi can
often make the moves work. :)

**Comment by nsajko** [comment]
I again set both colors to pachi, and both colors took c. 50 s for the first move and then made the others instantly, ending with a resign.
Maybe that's a gogui bug?

**Comment by pasky** [comment]
Sorry, not sure how else to help.  It might be interesting to get dump
of the GTP traffic and Pachi's -d 4 output.

**Comment by nsajko** [comment]
Here's the GTP log of pachi vs pachi, if it interests you:
[pachivspachi.gotxtp.txt](https://github.com/pasky/pachi/files/141347/pachivspachi.gotxtp.txt)

**Comment by pasky** [comment]
It seems to me that this is actually just a *single* pachi playing
against itself, and that might be getting the time management confused.
