### ISSUE TITLE
Adding "Deep learning" to the TODO list?

### ISSUE THREAD

**Issue by arbolis** [pasky/pachi#27]
Is machine learning/deep learning, etc. (things described to be in Alphago) going to be attempted to be implemented in pachi? Would it make sense to add this into the TODO list?

**Comment by pasky** [comment]
I don't plan to work on Pachi further personally.  Contributions in this direction would certainly be welcome, though!

**Comment by arbolis** [comment]
I wasn't aware of this. Let me thank you very much for everything you've done with pachi; this helped and inspired many other go programmers.

**Comment by pasky** [comment]
You're welcome!

And on a happy note, we just merged a very basic deep learning support, though only in the root node.
