### ISSUE TITLE
segment fault for dcnn

### ISSUE THREAD

**Issue by xlvector** [pasky/pachi#32]
in dcnn.cpp, function dcnn_get_moves, I find board->b is NULL.

But in uct/prior.c, function uct_prior_dcnn, I find map->b->b is NOT NULL.

This is strange, is it because of thread-safety?

**Comment by lemonsqueeze** [comment]
Hi,
This happens with current branch ?

**Comment by xlvector** [comment]
yes, current master branch.

Env: Mac, OS X Capitan 10.11.2

**Comment by xlvector** [comment]
yes, current master branch.

Env: Mac, OS X Capitan 10.11.2

**Comment by xlvector** [comment]
ubuntu can reproduce such problem

**Comment by xlvector** [comment]
Random seed: 1459840189
Loaded spatial dictionary of 1064482 patterns.
Loaded 2760778 pattern-probability pairs.
Initialized dcnn.
boardsize 19
IN: boardsize 19
=

Joseki dictionary for board size 19 loaded.
genmove b
IN: genmove b
Move:   0  Komi: 0.0  Handicap: 0  Captures B: 0 W: 0
      A B C D E F G H J K L M N O P Q R S T        A B C D E F G H J K L M N O P Q R S T
    +---------------------------------------+    +---------------------------------------+
 19 | . . . . . . . . . . . . . . . . . . . | 19 | . . . . . . . . . . . . . . . . . . . |
 18 | . . . . . . . . . . . . . . . . . . . | 18 | . . . . . . . . . . . . . . . . . . . |
 17 | . . . . . . . . . . . . . . . . . . . | 17 | . . . . . . . . . . . . . . . . . . . |
 16 | . . . . . . . . . . . . . . . . . . . | 16 | . . . . . . . . . . . . . . . . . . . |
 15 | . . . . . . . . . . . . . . . . . . . | 15 | . . . . . . . . . . . . . . . . . . . |
 14 | . . . . . . . . . . . . . . . . . . . | 14 | . . . . . . . . . . . . . . . . . . . |
 13 | . . . . . . . . . . . . . . . . . . . | 13 | . . . . . . . . . . . . . . . . . . . |
 12 | . . . . . . . . . . . . . . . . . . . | 12 | . . . . . . . . . . . . . . . . . . . |
 11 | . . . . . . . . . . . . . . . . . . . | 11 | . . . . . . . . . . . . . . . . . . . |
 10 | . . . . . . . . . . . . . . . . . . . | 10 | . . . . . . . . . . . . . . . . . . . |
  9 | . . . . . . . . . . . . . . . . . . . |  9 | . . . . . . . . . . . . . . . . . . . |
  8 | . . . . . . . . . . . . . . . . . . . |  8 | . . . . . . . . . . . . . . . . . . . |
  7 | . . . . . . . . . . . . . . . . . . . |  7 | . . . . . . . . . . . . . . . . . . . |
  6 | . . . . . . . . . . . . . . . . . . . |  6 | . . . . . . . . . . . . . . . . . . . |
  5 | . . . . . . . . . . . . . . . . . . . |  5 | . . . . . . . . . . . . . . . . . . . |
  4 | . . . . . . . . . . . . . . . . . . . |  4 | . . . . . . . . . . . . . . . . . . . |
  3 | . . . . . . . . . . . . . . . . . . . |  3 | . . . . . . . . . . . . . . . . . . . |
  2 | . . . . . . . . . . . . . . . . . . . |  2 | . . . . . . . . . . . . . . . . . . . |
  1 | . . . . . . . . . . . . . . . . . . . |  1 | . . . . . . . . . . . . . . . . . . . |
    +---------------------------------------+    +---------------------------------------+

desired 13.50, worst 15.00, clock [1] 0.00 + 15.00/1*1, lag 2.25
[1]    72763 segmentation fault  ./pachi

**Comment by xlvector** [comment]
I can solve this problem by only do following function in dcnn.cpp. 

void
dcnn_get_moves1(float *data, float result[])
{
  int size = 19;
        Blob<float> *blob = new Blob<float>(1,2,size,size);
        blob->set_cpu_data(data);
        vector<Blob<float>*> bottom;
        bottom.push_back(blob);
        assert(net);
        const vector<Blob<float>*>& rr = net->Forward(bottom);

        for (int i = 0; i < size * size; i++) {
                result[i] = rr[0]->cpu_data()[i];
                if (result[i] < 0.00001)
                        result[i] = 0.00001;
        }
        //delete[] data;
        delete blob;
}

And generate float * data in uct/prior.c uct_dcnn_prior function, and then call above function.

I am not good at C/C++, so I do not know while previous implement does not work in my ubuntu or mac system.

**Comment by xlvector** [comment]
From http://computer-go.org/pipermail/computer-go/2015-April/007573.html

it seems the prediction rate of net.tgz is 44%.

this mail publish a 54% dcnn http://computer-go.org/pipermail/computer-go/2015-December/008324.html

**Comment by lemonsqueeze** [comment]
Good catch, i'm curious how it's going to do with the 54% network. The inputs are different but no big deal. Should be able to try soon...

Regarding the crash not sure what's going on here, for me it just works
(ubuntu 14 x64, gcc/g++ 4.8, caffe from git repo + openblas)
I know i got weird segmentation faults at first when compiling with clang. You wouldn't be using clang by any chance ?

**Comment by xlvector** [comment]
I also get segmentation faults under:

Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-42-generic x86_64)
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
caffe from git repo + openblas

I also use gdb to debug the program and find that the map->b pointer address is right after pass to dcnn_get_moves function, but member address of board b is changed...

I do not know if is it because pass struct * board from C to C++ code?

P.S.

I use following code to generate input for 54% network, but get poor results...


static float*
dcnn2_get_moves_data(struct board *b, enum stone color)
{
	assert(real_board_size(b) == 19);
	int size = 19;
	int dsize = 13 * size * size;
	float *data = (float *)malloc(dsize * sizeof(float));
	for (int i = 0; i < dsize; i++) {
		data[i] = 0.0;
	}
	for (int j = 0; j < size; j++) {
		for(int k = 0; k < size; k++) {
			int p = size * j + k;
			coord_t c = coord_xy(b, j+1, k+1);
			struct group g = b->gi[c];
			enum stone bc = board_at(b, c);
			int libs = g.libs - 1;
			if (libs < 0) libs = 0;
			if (libs > 3) libs = 3;
			if(bc == S_NONE) {
				data[8*size*size + p] = 1.0;
			} else if (bc == color) {
				data[(0+libs)*size*size + p]=1.0;
			} else if (bc == stone_other(color)) {
				data[(4+libs)*size*size + p]=1.0;
			}
			if(c == b->last_move.coord) {
				data[9*size*size + p] = 1.0;
			} else if (c == b->last_move2.coord) {
				data[10*size*size + p] = 1.0;
			} else if (c == b->last_move3.coord) {
				data[11*size*size + p] = 1.0;
			} else if (c == b->last_move4.coord) {
				data[12*size*size + p] = 1.0;
			}
		}
	}

	return data;
}

**Comment by lemonsqueeze** [comment]
That's really weird, looks like we have exactly same setup.
Which command did you use to run pachi ? (threads, etc)

**Comment by xlvector** [comment]
I use default command, just  ./pachi

**Comment by xlvector** [comment]
static float*
dcnn2_get_moves_data(struct board *b, enum stone color)
{
	assert(real_board_size(b) == 19);
	int size = 19;
	int dsize = 13 * size * size;
	float *data = (float *)malloc(dsize * sizeof(float));
	for (int i = 0; i < dsize; i++) {
		data[i] = 0.0;
	}
	for (int j = 0; j < size; j++) {
		for(int k = 0; k < size; k++) {
			int p = size * j + k;
			coord_t c = coord_xy(b, j+1, k+1);
			struct group g = board_group_info(b, group_at(b, c));
			enum stone bc = board_at(b, c);
			int libs = g.libs - 1;
			if (libs > 3) libs = 3;
			if(bc == S_NONE) {
				data[8*size*size + p] = 1.0;
			} else if (bc == color) {
				data[(0+libs)*size*size + p]=1.0;
			} else if (bc == stone_other(color)) {
				data[(4+libs)*size*size + p]=1.0;
			}
			if(c == b->last_move.coord) {
				data[9*size*size + p] = 1.0;
			} else if (c == b->last_move2.coord) {
				data[10*size*size + p] = 1.0;
			} else if (c == b->last_move3.coord) {
				data[11*size*size + p] = 1.0;
			} else if (c == b->last_move4.coord) {
				data[12*size*size + p] = 1.0;
			}
		}
	}
	return data;
}

above code works find with 54% CNN from http://computer-go.org/pipermail/computer-go/2015-December/008324.html

**Comment by lemonsqueeze** [comment]
If you want to try valgrind i'd recommend caffe + atlas instead of caffe + openblas.
Here's the command i use:
`valgrind --fair-sched=yes --trace-children=yes ./pachi ...`

**Comment by lemonsqueeze** [comment]
I was able to look at the crash with xlvector. Turns out it was caused by a build issue (building with MAC=1 on Ubuntu). I could confirm current code works fine on Ubuntu under correct build.
There might still be issues on mac (haven't tested mac build at all)
