### ISSUE TITLE
seki basic problem 

### ISSUE THREAD

**Issue by pw31** [pasky/pachi#39]
Hi there,

I just installed pachi 11.99 with book.dat, patterns, and dcnn support. I am running it on a 24-core Linux machine. It's a great program, too strong for me, I enjoy playing it a lot!

The game below demonstrates, however, that pachi (W) seems to have a some problem with seki. Around move #135, pachi engaged into a "killing variation" that would have decided the game, if it worked.  But the truth is, it's only seki, very basic one, so B was alive.  Pachi didn't stop playing and was still claiming to win until the very end ...

When I tried programming go myself, this was one of the basic problems that I couldn't solve. During play-outs, when to stop filling in stones, and when to continue. Some go knowledge seems to be necessary.  Pachi seems not to try continuing in this case.

Maybe, the position around move #135 is a good test case.

Thanks for pachi.  Peter 

(;FF[4]CA[UTF-8]AP[GoGui:1.4.9]
HA[4]PB[pw31]PW[Pachi 11.99 on auriga 24 cores]DT[2016-04-30]RE[B+33]
AB[dp][pd][dd][pp]PL[W];W[qf];B[qh];W[of];B[nd];W[pi];B[ph];W[oh];B[qi];W[pj];
B[qj]
;W[pk];B[ql];W[om];B[qn];W[lc];B[ld];W[kd];B[le];W[mc];B[nc]
;W[md];B[me];W[ne];B[kc];W[kb];B[jc];W[jb];B[ic];W[nb];B[ob]
;W[ib];B[hc];W[hb];B[gc];W[cj];B[ce];W[mb];B[gb];W[cn];B[fq]
;W[rd];B[bp];W[en];B[bn];W[co];B[bo];W[cp];B[cq];W[cm];B[bm]
;W[cl];B[mg];W[ng];B[mh];W[qc];B[nh];W[og];B[oe];W[nf];B[pc]
;W[mf];B[lf];W[lg];B[je];W[kg];B[jf];W[li];B[ih];W[qb];B[nj]
;W[oi];B[lj];W[kj];B[lk];W[kk];B[ch];W[ll];B[kl];W[jl];B[km]
;W[ml];B[jm];W[il];B[im];W[hl];B[hm];W[gl];B[fo];W[nq];B[lq]
;W[pq];B[qq];W[qr];B[oq];W[pr];B[or];W[op];B[nr];W[np];B[mq]
;W[qp];B[po];W[rp];B[nn];W[mn];B[mo];W[ln];B[ko];W[kn];B[jo]
;W[jn];B[io];W[dh];B[cg];W[gh];B[di];W[ci];B[eh];W[dj];B[ei]
;W[gj];B[gg];W[rm];B[rl];W[qm];B[pl];W[pm];B[qk];W[rg];B[ol]
;W[nm];B[rh];W[ni];B[rj];W[si];B[sh];W[sk];B[sl];W[sj];B[qg]
;W[re];B[pf];W[pg];B[pe];W[mj];B[no];W[rf];B[rn];W[sm];B[ej]
;W[ek];B[fk];W[fl];B[el];W[dk];B[fm];W[em];B[fn];W[bh];B[bl]
;W[bg];B[bf];W[dg];B[cf];W[eg];B[fg];W[fh];B[ef];W[fj];B[df]
;W[ga];B[fa];W[ha];B[fb];W[pn];B[qo];W[sn];B[oo];W[rr];B[bk]
;W[hh];B[bj];W[bi];B[hg];W[in];B[hn];W[eo];B[ep];W[lo];B[lp]
;W[jg];B[ig];W[kf];B[ke];W[la];B[ii];W[gm];B[sg];W[gn];B[go]
;W[lm];B[ho];W[mi];B[sf];W[pb];B[se];W[sd];B[oc];W[oa];B[ai]
;W[ij];B[ag];W[ah];B[af];W[aj];B[ak];W[ji];B[ai];W[nk];B[nl]
;W[ro];B[ok];W[do];B[oj];W[mk];B[jh];W[kh];B[fi];W[gi];B[hj]
;W[hk];B[hi];W[gk];B[jk];W[os];B[ns];W[ps];B[lr];W[qd];B[bq]
;W[qe];B[aj];W[ck];B[ec];W[od];B[mp];W[mm];B[on];W[lh];B[]
;W[dl];B[];W[so];B[];W[jj];B[];W[sr];B[];W[ik];B[]
;W[lk];B[];W[oe];B[];W[ma];B[];W[pd];B[];W[lj]
C[W doesn't stop playing ...
W simply doesn't understand the seki on the right hand side]
)

**Comment by lemonsqueeze** [comment]
Hi, this game is a very good test case for seki, thanks.

**Comment by pw31** [comment]
Just want to say that after code update 12/07/2016 the problem seems to have been fixed.  Pachi still plays the seki with 135. t11 t12 t9 t8 t10 (because dcnn suggests it), which is not necessarily bad, but then counts correctly and evaluates win probability ~40% for white afterwards - THANKS!
