### ISSUE TITLE
Fix for H9 games

### ISSUE THREAD

**Issue by lemonsqueeze** [pasky/pachi#40]
Hi,

I noticed Pachi resigns 9 stones handicap games as white.
Looks like passing  `dynkomi=linear:handicap_value=8%8` fixes it,
Shouldn't it be the default ?

**Comment by pasky** [comment]
If you look at the history of uct/dynkomi.c, you see that jlg progressively reduced handi value in pachi-as-white games as it improved performance for lower-handi games.  In 4-handi game, 32 komi vs. 4 komi at the beginning is a huge difference. Maybe a better+simpler fix would be to just prohibit resignation in first ~50 moves.

**Comment by lemonsqueeze** [comment]
Ok, good to know.

**Comment by lemonsqueeze** [comment]
Fixed by PR #73
