### ISSUE TITLE
windows toolchain variants and WIN macro confusion

### ISSUE THREAD

**Issue by sthalik** [pasky/pachi#5]
The issue's with the WIN macro. There's no homogenous Windows build target, e.g. one that has or has no <regex.h>.

Note that, for instance, CMake doesn't define WIN32 on Cygwin. Cygwin's not Win, it's Unix. It *is* POSIX.

OTOH, mingw-w64 *is* WIN32. It's a compat wrapper to build the GNU toolchain and some simple, short headers for missing POSIX functionality.

Fix the confusion with WIN Makefile stuff, seeing here choices:

- treat as WIN32_NO_POSIX, remove "#include \<regex.h\>" and so forth which isn't in C89 but POSIX only. Remove confusing text about performance issues.
- add another macro for mingw variants, so that it builds
- pretend problem doesn't exist
 
See also forthcoming pull request.

**Comment by pasky** [comment]
I'm closing this, hoping we figured this out with PR #24. :) Please reopen if not.
