### ISSUE TITLE
Can pachi be used with Caffe and Nvidia Docker containers?

### ISSUE THREAD

**Issue by JDJoe** [pasky/pachi#75]
I got NVIDIA CUDA 9.0 + cuDNN + tensorflow etc up and running (for Leela_Zero) but never managed to get Caffe up and running so I thought about going with Docker's NVIDIA and Caffe containers for Pachi.

Before I start to build all that, can Pachi be built/use Docker containers? 
If so, perhaps you can give me few pointers how to get it up an running. My experience with Docker is rather limited.

**Comment by lemonsqueeze** [comment]
This is for Windows I guess ?

**Comment by JDJoe** [comment]
> This is for Windows I guess ?

No. Kubuntu 17.10, with  4.14.13 kernel and nvidia-387 driver, GeForce GTX 1080 Ti

**Comment by lemonsqueeze** [comment]
Actually setting up Caffe for Ubuntu >= 17.04 should be easy, there are [packages](http://caffe.berkeleyvision.org/install_apt.html) in the repositories now.
 `sudo apt-get install libcaffe-cuda-dev` should give you everything you need for the gpu version (or `libcaffe-cpu-dev` for the cpu version).

Really don't know for the docker container. As long as there's a compiler in it, caffe + dependencies libs and headers it should work.

**Comment by JDJoe** [comment]
Thanks. How did I miss that :) 
Compiled with 

```
DCNN=1
CAFFE_PREFIX=/usr/include/caffe/
```
no problems there but when I run this new version, I can see it working hard my CPU's but no load on GPU. 

I can see it with $ nvidia-smi 

`|    0     15192      C   /usr/local/bin/pachi                         189MiB`

But this is about it. GPU show no workload as it does with other programs using GPU.
