### ISSUE TITLE
losing games because pachi refuses to stop / keeps filling eyes, ignores pass

### ISSUE THREAD

**Issue by JDJoe** [pasky/pachi#76]
It seems that pachi has no idea when to stop playing. 
For example, I used: 
 
`-f book.dat -t _1200 -e dcnn -t =5000:15000 threads=4,max_tree_size=3072`

adding `maximize_score` had no positive effect. 

Opponent keeps passing while pachi fills up his own eyes and then loses the game.

**Comment by lemonsqueeze** [comment]
`-e dcnn`: you're using the barebones dcnn-only engine which as you've discovered very faithfully always plays dcnn's best move even when it makes no sense.

If you want pachi to play a real game use uct, the default engine, which is mcts + dcnn. Pachi will know when to pass and when to resign.

The command you're using also has conflicting time options. I would start with something simple like:

    ./pachi -t =5000:15000 threads=4,max_tree_size=100

and change options one at a time if needed. 
`-f book.dat` is probably not very useful nowadays, dcnn can deal with fuseki.

**Comment by JDJoe** [comment]
> ./pachi -t =5000:15000 threads=4,max_tree_size=100

Thank you. This is much better.

**Comment by lemonsqueeze** [comment]
> If you have any recommendation how to squeeze the max out of my Nvidia GPU, please post here.

Right now Pachi only uses dcnn for root node so your gpu will be mostly idle.  
If you want to put it to work try [Leela](https://www.sjeng.org/leela.html),  [Darkforest](https://github.com/facebookresearch/darkforestGo), [Raynn](https://github.com/zakki/Ray/tree/nn) or [AQ](https://github.com/ymgaq/AQ/), they use of policy / value networks extensively.
