### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by GD-fix** [pasky/pachi#78]
Linux all error:
"make: *** No rule to make target `.git/HEAD', needed by `build.h'.  Stop."

**Comment by lemonsqueeze** [comment]
Hi, looks like you don't have a git repository. Which sources are you using ?

**Comment by GD-fix** [comment]
Hi!
Zip archive from here.

**Comment by lemonsqueeze** [comment]
In this case try editing Makefile replacing :
    
    build.h: .git/HEAD .git/index Makefile

with:

    build.h:  Makefile

You should be able to build then. Otherwise with git:

    git clone https://github.com/pasky/pachi
    cd pachi
    make

**Comment by GD-fix** [comment]
Thanks!
I will try.
With git will not be work: it's a local only PC...

**Comment by GD-fix** [comment]
Hi!

It works.
Is it possible to add in Makefile net probing and appropriate choosing of "build.h:" parameters (and for modern PC to do DOUBLE_FLOATING=1 by default and increase spatial_hash_bits) in next version?

Thanks.
