### ISSUE TITLE
Doesn't compile on local PC (without Internet)

### ISSUE THREAD

**Issue by GD-fix** [pasky/pachi#85]
Doesn't compile (because that PC is local only) - I had downloaded zip archive and extracted its content. While bazel build: 
> ERROR: error loading package...

How to compile on local PC (OS: openSUSE Tumbleweed)?

Thanks in advance.

**Comment by lemonsqueeze** [comment]
Hi,

Try `make` instead, Pachi doesn't use bazel to build.

Right now it's best to have a git repository to build.  Once you have the repository you don't need internet connection though, so if you want to build on a local pc without internet connection just clone and zip the repository first and copy it over to the local pc.

With the zip archive you won't have a repository. It's still possible to build but you'll have to tweak the Makefile. Try [this](https://github.com/pasky/pachi/issues/78#issuecomment-375922538) from issue #78.

**Comment by GD-fix** [comment]
Hi!

Thanks!
I will try.

**Comment by GD-fix** [comment]
Hi!

I'm sorry! 
It works, of course. I had tried to build with Bazel because I had read another READme....
