### ISSUE TITLE
segfault or assertion failures with 9x9 and free handicap

### ISSUE THREAD

**Issue by dvdkhlng** [pasky/pachi#86]
Hi,

the following sequence of GTP commands crashes pachi (master):

    /usr/local/bin/pachi -d3 --nodcnn -t =40000 -f book.dat threads=4,maximize_score

    boardsize 9
    set_free_handicap C3 G7 C7
    komi 0
    genmove w

    pachi: ../board.h:629: board_get_atari_neighbor: Assertion `coord != pass' failed.

with the following command line I get a segfault:

    /usr/local/bin/pachi -d3 --nodcnn -t 10 -f book.dat threads=4,maximize_score

    Thread 7 "pachi" received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7fffb2dac700 (LWP 10855)]
    0x00005555555a9c3e in ?? ()
    (gdb) bt
    #0  0x00005555555a9c3e in ?? ()
    #1  0x00005555555856d0 in playout_play_move ()
    #2  0x0000555555585926 in playout_play_game ()
    #3  0x000055555558c595 in uct_mcowner_playouts ()
    #4  0x0000555555591543 in ?? ()
    #5  0x00007ffff652f494 in start_thread (arg=0x7fffb2dac700)
	at pthread_create.c:333
    #6  0x00007ffff6271acf in clone ()

**Comment by dvdkhlng** [comment]
Ok, I think this is related to using an opening book.  Seems that without "-f book.dat" pachi runs fine.

**Comment by lemonsqueeze** [comment]
Strange, couldn't replicate this one even with old code.
Is this still happening ? If so, please reopen issue.
